### ISSUE TITLE
Type declaration file not available on the packaged lib

### ISSUE THREAD

**Issue by gabriellett** [JamesEggers1/node-ABAValidator#5]
After PR #4 , I was expecting type declarations to be available on the package, but looks like it's not there still.

When building the package locally with `npm run build`, type declarations are correctly saved on the dist file as:
```
export declare function validate(routingNumber: string): boolean;
//# sourceMappingURL=aba-validation.d.ts.map
```

Looking at other files on dist, it appears that my output from `npm run build` will generate different files from the files available on the packaged lib. I'm using node 10 as described on the package.json.

Seems like the package was not built before publishing the library. Not sure if you have this automated or was just a manual issue.

**Comment by JamesEggers1** [comment]
You are correct - I was in a rush and completely forgot to rebuild the package before publishing it to npm.  I have updated the build to 3.1.1 which have the updated definitions.  Sorry about that and thank you again for your assistance.

**Comment by gabriellett** [comment]
@JamesEggers1 Cheers mate, thanks! Let me know if this change has any unforeseen effect on your side
